aliases: []
creation_timestamp: 1740310456244
current_stage: None
description: null
last_updated_timestamp: 1740310456244
name: BestModel
run_id: 5e58f2e5cfdf481cac001d35b6616523
run_link: null
source: file:C:/Users/samir/Desktop/rakuten-mlops/${MLFLOW_TRACKING_URI}/430307742026791296/5e58f2e5cfdf481cac001d35b6616523/artifacts/xgb_model
status: READY
status_message: null
storage_location: file:C:/Users/samir/Desktop/rakuten-mlops/${MLFLOW_TRACKING_URI}/430307742026791296/5e58f2e5cfdf481cac001d35b6616523/artifacts/xgb_model
user_id: null
version: 1
