artifact_location: file:C:/Users/samir/Desktop/rakuten-mlops/${MLFLOW_TRACKING_URI}/0
creation_time: 1740310425143
experiment_id: '0'
last_update_time: 1740310425143
lifecycle_stage: active
name: Default
